# Basic Python Types

This lesson covers:

* Inputting scalars and strings
* Lists
* Dictionaries


## Problem: Input scalar floating point and integers

1. Create a variable called `scalar_float` containing $\pi$ to 4 digits.
2. Create a variable called `scalar_int` containing 31415. 
3. Print each value using the `print` function.   

In [1]:
scalar_float = 3.1415
scalar_int = 31415

print(scalar_float)
print(scalar_int)

3.1415
31415


## Problem: Create a string and an f-string

1. Create a variable called `a_string` containing `This is a string`
2. Create a f-string the prints `The value of scalar_float is 3.1415` using
   the variable created in the previous step
3. Create two string, `first` containing `String concatenation` and the second containing
   ` is like addition`, and join the two using `+` to produce
   `String concatenation is like addition`. 

In [2]:
a_string = "This is a string"
# Either quote mark is fine, as long as they match
a_string = 'This is a string'

print(f'The value of scalar_float is {scalar_float}')
print(f'The value of scalar_int is {scalar_int}')

first = "String concatenation"
second = " is like addition"
print(first + second)

The value of scalar_float is 3.1415
The value of scalar_int is 31415
String concatenation is like addition


## Problem: Create a list

1. Create a list containing `scalar_float` and `scalar_int`
2. Add `a_string` to the list.
3. Select the the lst two elements of the list

In [3]:
a_list = [scalar_float, scalar_int]
print(a_list)
a_list.append(a_string)
print(a_list)

end_of_a_list = a_list[1:]
other_wa = a_list[-2:]

[3.1415, 31415]
[3.1415, 31415, 'This is a string']


## Problem: Create a list of lists

1. Create a list containing the two lists `[1, 2, 3]` and `[4, 5, 6]`
2. Select the element 5 from the nested list

In [4]:
second_list = [[1, 2, 3], [4, 5, 6]]
second_row = second_list[1]
print(second_row)
number_5 = second_row[1]
print(number_5)
number_5_direct = second_list[1][1]
print(number_5_direct)

[4, 5, 6]
5
5


## Problem: Create a dictionary

1. Create a dictionary containing the key-value pairs `"float"` and 3.1415, `"int"` and 31415,
   and `"string"` and `"three-point-one-four-one-five"`.

In [5]:
a_dict = {"float": 3.1415,
          "int": 31415,
          "string": "three-point-one-four-one-five"}
 
print(a_dict)

{'float': 3.1415, 'int': 31415, 'string': 'three-point-one-four-one-five'}


## Problem: Lookup and Change a value

1. Look up the value of `"float"`.
2. Change the value of `"float"` to `22 / 7`.

In [6]:
print(a_dict["float"])
a_dict["float"] = 22 / 7
print(a_dict["float"])

3.1415
3.142857142857143


## Problem: Add and remove a key 

1. Add the new key "better_float" with the value 3.141592.
2. Remove the key "float" and its value.

In [7]:
a_dict["better_float"] = 3.141592
print(a_dict)

del a_dict["float"]
print(a_dict)

{'float': 3.142857142857143, 'int': 31415, 'string': 'three-point-one-four-one-five', 'better_float': 3.141592}
{'int': 31415, 'string': 'three-point-one-four-one-five', 'better_float': 3.141592}
